# Generated by Django 4.1.3 on 2022-12-18 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_answers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'verbose_name': 'Ответить', 'verbose_name_plural': 'Ответы'},
        ),
    ]
