# Generated by Django 4.1.3 on 2022-12-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_answers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={},
        ),
    ]
